<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="AlbumGUI.aspx.cs" Inherits="SE1432_Group2_Lab4.WebForm4" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <p style="font-size: 30px; font-weight: bold;">
    List of Album</p>
<p>
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" DataKeyNames="AlbumID" DataSourceID="ObjectDataSource1" Width="1057px" BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" CellPadding="4" EnableModelValidation="True">
        <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
        <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
        <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
        <RowStyle BackColor="White" ForeColor="#003399" />
        <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
        
    </asp:GridView>
</p>
<p>
    <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" SelectMethod="GetDataTable" TypeName="SE1432_Group2_Lab4.DTL.AlbumDAO" DataObjectTypeName="SE1432_Group2_Lab4.DTL.Album" DeleteMethod="Delete"></asp:ObjectDataSource>
</p>
<p>
    <asp:Button ID="BtAdd" runat="server" BackColor="Black" BorderColor="White" Text="Add" ForeColor="White" OnClick="BtAdd_Click" Width="70px" />
    <asp:Button ID="BtEddit" runat="server" Text="Edit" BackColor="Black" ForeColor="White" OnClick="BtEddit_Click" Width="70px" style="margin-left: 36px" />
    <asp:Label ID="LblError" runat="server"  BorderColor="Red" ForeColor="Red" Font-Size="Medium"></asp:Label>
</p>
<p>
    &nbsp;</p>
<p>
    &nbsp;</p>
</asp:Content>
